### ISSUE TITLE
Menu doesn't show other sub-menu items after one is selected. 

### ISSUE THREAD

**Issue by jdisano** [asuengineering/asu-labs-theme#5]
**Issue**
When clicking an item in the menu that contains sub-menu items, the menu collapses after a sub-menu item is selected. The user has to continually click the main menu item to see the other choices in the sub-menu.

**To reproduce**
1. Click on a menu item, e.g. People.
2. Click on a sub-menu item, e.g. Directory. 
3. Note that the other sub-menu items are longer displayed.

**Expected behavior**
Menu should stay expanded once a sub-menu item is selected. Selected menu item should be highlighted to indicate what page the user is on

**Screenshot**
<img width="400" alt="screen shot 2019-02-27 at 8 25 24 pm" src="https://user-images.githubusercontent.com/47798804/53539799-3ea32a80-3ad0-11e9-85ab-c5e78d538079.png">

**Comment by SteveRyan-ASU** [comment]
Looking for some additional design patterns in other places to understand whether this is a design norm or something that breaks the rules.

**Comment by jdisano** [comment]
Not sure if this helps but the screenshot I added is from Foundation.

**Comment by jdisano** [comment]
https://foundation.zurb.com/sites/docs/rtl.html
https://getbootstrap.com/docs/4.3/layout/grid/

**Comment by SteveRyan-ASU** [comment]
Settling into a potential fix for this problem. There are two different points to think through. 

The first is the state of the dropdown menu when a "sub-page" is the active page. There are lots of working examples to indicate that it's a good idea to leave the menu panel **open** when a page is loaded that sits inside of a collapsible element. 

Within the ASU design system, there are distinct styles that are applied to the **parent** and **child** items within a navigation menu that contains a mega-menu or a simple dropdown menu. The ASU Labs menu items maintain that pattern, so no changes to the colors used within the menu are really needed here.

**Comment by SteveRyan-ASU** [comment]
![image](https://user-images.githubusercontent.com/2085753/59632048-20544f80-90fe-11e9-9477-0dcf297cc5ae.png)
